apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devel-root-application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: devel
  source:
    path: cluster-test-charts/
    repoURL: https://github.com/martinjankovic/k8-gitops-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
